INSERT INTO ARTICLE(ID, TITLE, CONTENT) VALUES(1, '가가가가', '1111');
INSERT INTO ARTICLE(ID, TITLE, CONTENT) VALUES(2, '나나나나', '2222');
INSERT INTO ARTICLE(ID, TITLE, CONTENT) VALUES(3, '다다다다', '3333');

INSERT INTO MEMBER(ID, EMAIL, PASSWORD) VALUES(1, 'yooboong22@gmail.com', '1111');
INSERT INTO MEMBER(ID, EMAIL, PASSWORD) VALUES(2, 'yooboong222@gmail.com', '2222');
INSERT INTO MEMBER(ID, EMAIL, PASSWORD) VALUES(3, 'yooboong223@gmail.com', '3333');