INSERT INTO ARTICLE(TITLE, CONTENT) VALUES('가가가가', '1111');
INSERT INTO ARTICLE(TITLE, CONTENT) VALUES('나나나나', '2222');
INSERT INTO ARTICLE(TITLE, CONTENT) VALUES('다다다다', '3333');

INSERT INTO MEMBER(EMAIL, PASSWORD) VALUES('yooboong22@gmail.com', '1111');
INSERT INTO MEMBER(EMAIL, PASSWORD) VALUES('yooboong222@gmail.com', '2222');
INSERT INTO MEMBER(EMAIL, PASSWORD) VALUES('yooboong223@gmail.com', '3333');