INSERT INTO ARTICLE(TITLE, CONTENT) VALUES('가가가가', '1111');
INSERT INTO ARTICLE(TITLE, CONTENT) VALUES('나나나나', '2222');
INSERT INTO ARTICLE(TITLE, CONTENT) VALUES('다다다다', '3333');

INSERT INTO ARTICLE(TITLE, CONTENT) VALUES('당신의 인생 영화는?', '댓글 고');
INSERT INTO ARTICLE(TITLE, CONTENT) VALUES('당신의 소울 푸드는?', '댓글 고고');
INSERT INTO ARTICLE(TITLE, CONTENT) VALUES('당신의 취미는?', '댓글 고고고');

INSERT INTO COMMENT(ARTICLE_ID, NICKNAME, BODY) VALUES(4,'Park', '굿 윌 헌팅');
INSERT INTO COMMENT(ARTICLE_ID, NICKNAME, BODY) VALUES(4,'Kim', '아이 엠 샘');
INSERT INTO COMMENT(ARTICLE_ID, NICKNAME, BODY) VALUES(4,'Choi', '쇼생크 탈출');

INSERT INTO COMMENT(ARTICLE_ID, NICKNAME, BODY) VALUES(5,'Park', '치킨');
INSERT INTO COMMENT(ARTICLE_ID, NICKNAME, BODY) VALUES(5,'Kim', '샤브샤브');
INSERT INTO COMMENT(ARTICLE_ID, NICKNAME, BODY) VALUES(5,'Choi', '초밥');

INSERT INTO COMMENT(ARTICLE_ID, NICKNAME, BODY) VALUES(6,'Park', '조깅');
INSERT INTO COMMENT(ARTICLE_ID, NICKNAME, BODY) VALUES(6,'Kim', '유튜브 시청');
INSERT INTO COMMENT(ARTICLE_ID, NICKNAME, BODY) VALUES(6,'Choi', '독서');


INSERT INTO MEMBER(EMAIL, PASSWORD) VALUES('yooboong22@gmail.com', '1111');
INSERT INTO MEMBER(EMAIL, PASSWORD) VALUES('yooboong222@gmail.com', '2222');
INSERT INTO MEMBER(EMAIL, PASSWORD) VALUES('yooboong223@gmail.com', '3333');

INSERT INTO COFFEE(NAME, PRICE) VALUES('아메리카노', '4500');
INSERT INTO COFFEE(NAME, PRICE) VALUES('라떼', '5000');
INSERT INTO COFFEE(NAME, PRICE) VALUES('카페 모카', '5500');